//! Database queries

pub mod communication;
pub mod inbox_state;
pub mod planned_action;
pub mod scoring;
pub mod country;
pub mod customer;
pub mod device;
pub mod device_type_config;
pub mod import;
pub mod revision;
pub mod role;
pub mod route;
pub mod settings;
pub mod user;
pub mod crew;
pub mod visit;
pub mod task;
pub mod work_item;